In [42]:
###Задание 1
#Импортируйте библиотеку Numpy и дайте ей псевдоним np.
import numpy as np

In [43]:
#Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
#Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
#Будем считать, что каждый столбец - это признак, а строка - наблюдение.
a = np.array((1,2,3,3,1,8,8,11,10,7))
a = np.reshape(a, (2,5))
a = a.T
a
#Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
#Результат запишите в массив mean_a, в нем должно быть 2 элемента.
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.8])

In [44]:
###Задание 2
# Вычислите массив a_centered, отняв от значений массива а 
# средние значения соответствующих признаков, содержащиеся в массиве mean_a.
# Вычисление должно производиться в одно действие.
# Получившийся массив должен иметь размер 5x2.
a_centered = a - mean_a
a_centered

array([[-1. , -0.8],
       [ 0. , -0.8],
       [ 1. ,  2.2],
       [ 1. ,  1.2],
       [-1. , -1.8]])

In [66]:
### Задание 3
# Найдите скалярное произведение столбцов массива a_centered.
# В результате должна получиться величина a_centered_sp. 
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])
N = np.size(a[:,0])
sigma_sq = a_centered_sp / (N-1)
print(f'Несмещенная оценка: {sigma_sq}')

Несмещенная оценка: 1.5


In [67]:
### * Задание 4
# Число, которое мы получили в конце задания 3 является 
# ковариацией двух признаков, содержащихся в массиве а.
# В задании 3 мы делили сумму произведений центрированных 
# признаков на N-1, а не на N, поэтому полученная нами величина 
# является несмещенной оценкой ковариации.
# Подробнее узнать о ковариации можно здесь:
# https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html
# В этом задании проверьте получившееся число, вычислив
# ковариацию еще одним способом - с помощью функции np.cov.
# В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
# В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
# ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.
a_covT = np.cov(m=a.T)
print(f'a_covT: \n {a_covT}')
a_cov = a_covT[0,1]
print(f'a_cov: {a_cov}')
print(sigma_sq == a_cov)

a_covT: 
 [[1.  1.5]
 [1.5 2.7]]
a_cov: 1.5
True
